import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Description from "../components/Description";
import Footer from "../components/Footer";
import { compareDesc, format, parseISO } from "date-fns";
import { allPosts } from "contentlayer/generated";

export async function getStaticProps() {
  const posts = allPosts.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });
  return { props: { posts } };
}

function PostCard(post: any) {
  return (
    <div className=" flex justify-center w-4/6 md:w-1/2 lg:w-1/3 xl:w-1/4 2xl:w-1/5 mx-auto ">
      <Link href={post.url}>
        <ol className="relative border-l-2 border-gray-200  dark:border-neutral-700">
          <li className="mb-10 ml-6">
            <span className="absolute flex items-center justify-center w-6 h-6  rounded-full -left-3  ring-white dark:bg-neutral-800 bg-gray-200">
              <svg
                aria-hidden="true"
                className="w-3 h-3 text-neutral-600 dark:text-neutral-400 text-gray-600"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fill-rule="evenodd"
                  d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
                  clip-rule="evenodd"
                ></path>
              </svg>
            </span>
            <h3 className="flex text-start mb-1 text-md font-semibold text-gray-200 dark:text-white">
              {post.title}
            </h3>
            <div className="flex">
              <time className="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500 text-start mt-2">
                {post.date.slice(0, 10)}
              </time>
              <span
                className="bg-neutral-100 text-neutral-600 text-sm font-medium mr-2 px-2.5 py-0.5 rounded-md dark:text-gray-200 ml-3
                dark:border-neutral-700 dark:bg-neutral-800/70 border-2 "
              >
                {post.category}
              </span>
            </div>
            <div
              className="cl-post-body text-start text-gray-400 dark:text-gray-500"
              dangerouslySetInnerHTML={{ __html: post.description }}
            />
          </li>
        </ol>
      </Link>
    </div>
  );
}

export default function Home({ posts }: any) {
  return (
    <div>
      <Head>
        <title>Saul | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Description />
      <div className="mx-auto mt-2 -mb-16 text-center">
        {posts.map((post: any, idx: any) => (
          <PostCard key={idx} {...post} />
        ))}
      </div>
      <Footer />
    </div>
  );
}
